

MINIONS = [
  { :name => 'securityserver.one.one' },
  { :name => 'securityserver.two.one' },
  { :name => 'securityserver.three.one' },
  { :name => 'centralserver.one' },
  ]

MASTER_IP = "10.1.10.3"

vm_box = 'ubuntu/trusty64'

$bootstrapMinion = <<SCRIPT
  echo "#{MASTER_IP} saltmaster" >> /etc/hosts
  hostname `cat /etc/hostname`
  echo Updated hosts entry for 'salt' to #{MASTER_IP}
  wget -O install_salt.sh https://bootstrap.saltstack.com
  sh install_salt.sh
  echo "master: #{MASTER_IP}" >> /etc/salt/minion
  service salt-minion restart
  echo "LC_ALL=en_US.UTF-8" >> /etc/environment
SCRIPT

$bootstrapMaster = <<SCRIPT
  echo "LC_ALL=en_US.UTF-8" >> /etc/environment
  wget -O install_salt.sh https://bootstrap.saltstack.com
  sudo sh install_salt.sh -M -N
  echo "waiting for minions.."
  sleep 11
  salt-key -L
  salt-key -A -y
  salt '*' test.ping
  echo "setting up debs for all ..."
  echo "yes, i know there is better way, however this is what xroad install doc says ;)"
  salt '*server.*' cmd.run 'curl -s -q http://x-road.eu/.test/xroad/xroad_repo.gpg| sudo apt-key add -'
  salt '*server.*' cmd.run 'echo "deb file:/srv/xroad/debs trusty main" > /etc/apt/sources.list.d/xroad.list'
  salt '*server.*' cmd.run 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 00A6F0A3C300EE8C'
  salt '*server.*' cmd.run 'echo "deb http://ppa.launchpad.net/nginx/stable/ubuntu trusty main" >> /etc/apt/sources.list.d/xroad.list'
  salt '*server.*' cmd.run 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB9B1D8886F44E2A'
  salt '*server.*' cmd.run 'echo "deb http://ppa.launchpad.net/openjdk-r/ppa/ubuntu trusty main " >> /etc/apt/sources.list.d/xroad.list' 
  salt '*server.*' cmd.run 'apt-get update'
  salt-cp '*server.*' /tmp/xroad/scripts/debconf-set-selections.bash /usr/local/bin/debconf-set-selections.bash
  salt '*server.*' cmd.run "chmod 700 /usr/local/bin/debconf-set-selections.bash"
  salt '*server.*' cmd.run "/usr/local/bin/debconf-set-selections.bash"
  echo 'installing centralservers ..'
  salt 'centralserver.*' cmd.run "apt-get -q -y install xroad-centralserver"
  salt 'centralserver.*' cmd.run 'initctl list| grep xroad'
  salt 'centralserver.*' cmd.run "curl  -ks https://localhost:4000/login|wc -l"
  echo 'installing securityservers ..'
  salt 'securityserver.*' cmd.run "apt-get -q -y install xroad-securityserver"
  salt 'securityserver.*' cmd.run 'initctl list| grep xroad'
  salt 'securityserver.*' cmd.run "curl  -ks https://localhost:4000/login|wc -l"
  salt 'securityserver.*' cmd.run "curl  -s http://localhost:8083/login|wc -l"
  echo "you should see magic number 33"
  salt 'centralserver.*' test.ping
  #todo set up central server...
SCRIPT

Vagrant.configure('2') do |config|

 # The Minions
 MINIONS.each_with_index do |opts, i|
   i = i + 1
   #config.vm.define "xroad-0#{i}" do |minion|
   config.vm.define opts[:name] do |minion|
     minion.vm.box = vm_box
     minion.vm.synced_folder "../xroad", "/srv/xroad"
     ip = i + 3
     minion.vm.hostname = opts[:name] 
     minion.vm.network :private_network, ip: "10.1.10.#{ip}"
     config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      end
     # minion.vm.network :public_network, ip: "192.168.10.#{ip}"
     # Set master hostname
     minion.vm.provision :shell, :inline => $bootstrapMinion, :args => [MASTER_IP]
   end
 end
   # The Salt Master VM
 config.vm.define :saltmaster do |saltmaster|
   saltmaster.vm.box = vm_box
   saltmaster.vm.network :private_network, ip: "#{MASTER_IP}"
   saltmaster.vm.hostname = 'saltmaster'
   saltmaster.vm.provision "file", source: "../scripts/debconf-set-selections.bash", destination: "/tmp/xroad/scripts/debconf-set-selections.bash"
   saltmaster.vm.provision :shell, :inline => $bootstrapMaster

 end
end
